Repository cloudfoundry/app-autoscaler, pull requests merged in 2019-01, with the labels that each got.

#425 add metrics server test cases
  src/autoscaler/metricsserver/collector/collector.go
  src/autoscaler/metricsserver/collector/collector_suite_test.go
  src/autoscaler/metricsserver/collector/collector_test.go
  src/autoscaler/metricsserver/collector/envelope_processor.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
Labels: unscheduled

#419 Remove useless ticker
  src/autoscaler/eventgenerator/aggregator/metricPoller.go
  src/autoscaler/metricscollector/collector/app_streamer.go
  src/autoscaler/metricscollector/collector/collector.go
  src/autoscaler/metricscollector/collector/collector_test.go
Labels: unscheduled

#429 remove useless code
  src/autoscaler/metricscollector/cmd/metricscollector/main.go
  src/autoscaler/metricscollector/server/metric_handler.go
  src/autoscaler/metricscollector/server/metric_handler_test.go
  src/autoscaler/metricscollector/server/server.go
  src/autoscaler/metricscollector/server/server_suite_test.go
  src/autoscaler/metricscollector/service_client.go
Labels: unscheduled

#430 use server config when creating metrics collector server
  src/autoscaler/metricscollector/cmd/metricscollector/main.go
  src/autoscaler/metricscollector/server/server.go
  src/autoscaler/metricscollector/server/server_suite_test.go
Labels: unscheduled

#432 add http server for metrics query
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/metricsserver/collector/collector.go
  src/autoscaler/metricsserver/config/config.go
  src/autoscaler/metricsserver/config/config_test.go
  src/autoscaler/metricsserver/exampleconfig/example.yml
Labels: unscheduled

#421 emit envelops to metric server
  scripts/generate_test_certs.sh
  src/autoscaler/fakes/fake_emitter.go
  src/autoscaler/fakes/fake_wshelper.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_suite_test.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_test.go
  src/autoscaler/metricsgateway/config/config.go
  src/autoscaler/metricsgateway/config/config_suite_test.go
  src/autoscaler/metricsgateway/config/config_test.go
  src/autoscaler/metricsgateway/emitter.go
  src/autoscaler/metricsgateway/emitter_test.go
  src/autoscaler/metricsgateway/exampleconfig/example.yaml
  src/autoscaler/metricsgateway/helpers/helpers_suite_test.go
  src/autoscaler/metricsgateway/helpers/ws_helper.go
  src/autoscaler/metricsgateway/helpers/ws_helper_test.go
  src/autoscaler/metricsgateway/nozzle.go
  src/autoscaler/metricsgateway/nozzle_test.go
  src/autoscaler/metricsgateway/testhelpers/websocket_handler.go
  src/autoscaler/routes/routes.go
  src/autoscaler/routes/routes_test.go
  test-certs/metricserver.crt
  test-certs/metricserver.csr
  test-certs/metricserver.key
  test-certs/metricserver_client.crt
  test-certs/metricserver_client.csr
  test-certs/metricserver_client.key
  test-certs/metron.crt
  test-certs/metron.csr
  test-certs/metron.key
  test-certs/metron_client.crt
  test-certs/metron_client.csr
  test-certs/metron_client.key
  test-certs/reverselogproxy.crt
  test-certs/reverselogproxy.csr
  test-certs/reverselogproxy.key
  test-certs/reverselogproxy_client.crt
  test-certs/reverselogproxy_client.csr
  test-certs/reverselogproxy_client.key
Labels: delivered

#431 add config not to store instance metrics to db
  api/npm-shrinkwrap.json
  servicebroker/npm-shrinkwrap.json
  src/autoscaler/collection/TSDCache.go
  src/autoscaler/collection/TSDCache_test.go
  src/autoscaler/metricscollector/cmd/metricscollector/main.go
  src/autoscaler/metricscollector/collector/app_streamer.go
  src/autoscaler/metricscollector/collector/app_streamer_test.go
  src/autoscaler/metricscollector/collector/apppoller.go
  src/autoscaler/metricscollector/collector/apppoller_test.go
  src/autoscaler/metricscollector/collector/collector.go
  src/autoscaler/metricscollector/collector/collector_test.go
  src/autoscaler/metricscollector/config/config.go
  src/autoscaler/metricscollector/config/config_test.go
  src/autoscaler/metricscollector/server/metric_handler.go
  src/autoscaler/metricscollector/server/metric_handler_test.go
  src/autoscaler/metricscollector/server/server.go
  src/autoscaler/metricscollector/server/server_suite_test.go
  src/integration/components.go
Labels: delivered

#433 filter custom metrics
  src/autoscaler/metricsgateway/nozzle.go
  src/autoscaler/metricsgateway/nozzle_test.go
Labels: unscheduled

#434 fix unit test failure
  src/autoscaler/metricsgateway/emitter.go
  src/autoscaler/metricsgateway/emitter_test.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
Labels: unscheduled

#436 fix metrics server ut failure
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
Labels: unscheduled

#437 refine autoscaler docs
  README.md
  docs/Policy_definition.rst
  docs/Public_API.rst
  docs/Readme.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/css/style.scss
  docs/assets/js/main.js
  docs/dynamicpolicy.json
  docs/fullpolicy.json
  docs/policy.md
Labels: unscheduled

#441 revise user guide
  docs/Readme.md
Labels: unscheduled

#427 updated to incorporate review comments
  src/autoscaler/fakes/fake_metric_forwarder.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/exampleconfig/config.yml
  src/autoscaler/metricsforwarder/fakes/fake_cf_client.go
  src/autoscaler/metricsforwarder/fakes/fake_policy_db.go
  src/autoscaler/metricsforwarder/fakes/fakes.go
  src/autoscaler/metricsforwarder/forwarder/forwarder_test.go
  src/autoscaler/metricsforwarder/forwarder/metric_forwarder.go
  src/autoscaler/metricsforwarder/manager/policyManager.go
  src/autoscaler/metricsforwarder/manager/policyManager_test.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers_test.go
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsforwarder/server/server_suite_test.go
Labels: accepted

#452 Added more unit tests
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_suite_test.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_test.go
Labels: unscheduled

#450 fix bug "Wrong index and length parameters are provided when creating EnvelopeProcessors in metricsserver"
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
Labels: unscheduled

#447 rename metricsgateway tls relevant configurations
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_suite_test.go
  src/autoscaler/metricsgateway/config/config.go
  src/autoscaler/metricsgateway/config/config_test.go
  src/autoscaler/metricsgateway/exampleconfig/example.yaml
  src/integration/components.go
Labels: unscheduled
