Repository cloudfoundry/app-autoscaler, pull requests merged in 2021-09, with the labels that each got.

#693 Added Initalise db script
  README.md
  scripts/initialise_db.sh
Labels: enhancement, unscheduled

#700 Setting logicalFilePath for liquibase migrations to handle upgrade
  scheduler/db/quartz.changelog-master.yaml
  scheduler/db/scheduler.changelog-master.yaml
  src/autoscaler/api/db/api.db.changelog.yml
  src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml
  src/autoscaler/metricsserver/db/metricscollector.db.changelog.yml
  src/autoscaler/operator/db/operator.db.changelog.yml
  src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml
  src/autoscaler/servicebroker/db/servicebroker.db.changelog.json
Labels: bug, unscheduled

#701 Revert to liquibase 3 to ensure absolute paths can be used
  db/pom.xml
Labels: bug, unscheduled

#698 modified time in the tests not getting set and failing local tests
  src/autoscaler/db/sqldb/lock_sqldb_test.go
Labels: unscheduled, chore

#702 Added more descriptive information into the assert in app_test
  src/autoscaler/cf/app_test.go
Labels: unscheduled, chore

#708 Added or io.EOF error check to the tests to stablise them
  src/autoscaler/cf/app_test.go
Labels: unscheduled, exclude-from-changelog, chore

#707 Improved the pre-commit java format shell scripts
  style-guide/README.md
  style-guide/inspect-java-format-0.1.sh
Labels: unscheduled, exclude-from-changelog, chore

#692 Added basic auth options to the prometheus metrics endpoint.
  .github/workflows/mysql.yaml
  scheduler/pom.xml
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/MetricsConfig.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/MetricsConfiguration.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/conf/MetricsConfigurationTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/health/SchedulerHealthDefaultEndpointTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/health/SchedulerHealthEndpointTest.java
  scheduler/src/test/resources/application-HealthAuth.yml
Labels: enhancement, unscheduled, in progress, java

#709 Increased the timeout value for the ws_helper test
  src/autoscaler/metricsgateway/helpers/ws_helper.go
  src/autoscaler/metricsgateway/helpers/ws_helper_test.go
Labels: unscheduled, exclude-from-changelog, chore

#711 basic authentication added to healthcheck
  .github/workflows/generate.yaml
  src/autoscaler/api/config/config.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_test.go
  src/autoscaler/eventgenerator/config/config.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_test.go
  src/autoscaler/metricsgateway/config/config.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_suite_test.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_test.go
  src/autoscaler/metricsserver/config/config.go
  src/autoscaler/models/health.go
  src/autoscaler/operator/cmd/operator/operator_test.go
  src/autoscaler/operator/config/config.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/config/config.go
Labels: enhancement, unscheduled

#688 Feature: Creating a main makefile to encapsulate common build actions.
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  .gitignore
  Makefile
  README.md
  src/autoscaler/Makefile
Labels: unscheduled, go, exclude-from-changelog, chore

#714 Updates to allow GitHub actions to run locally
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  scripts/initialise_db.sh
  src/autoscaler/db/sqldb/binding_sqldb_test.go
Labels: exclude-from-changelog

#717 fix for the docker name being a regex
  Makefile
Labels: bug, exclude-from-changelog

#716 Display coverage when running golang unit tests
  src/autoscaler/Makefile
Labels: exclude-from-changelog

#715 Adding a .tool-versions to control developer versions
  .tool-versions
Labels: exclude-from-changelog

#720 Use jdk rather than jre in tool-versions
  .tool-versions
Labels: exclude-from-changelog

#725 fix syntax error in make file
  Makefile
  README.md
Labels: exclude-from-changelog, chore

#696 Adding mTLS authentication to the custom metrics endpoint
  .github/workflows/golangci-lint.yaml
  .gitignore
  scripts/generate_test_certs.sh
  src/autoscaler/.golangci.yaml
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
  src/autoscaler/metricsforwarder/server/auth/basic_auth.go
  src/autoscaler/metricsforwarder/server/auth/xfcc_auth.go
  src/autoscaler/metricsforwarder/server/auth_test.go
  src/autoscaler/metricsforwarder/server/common/varfunc.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers_test.go
  src/autoscaler/metricsforwarder/server/errors.go
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsserver/collector/ws_handler.go
Labels: enhancement, go

#722 Only touch files in the target folder
  Makefile
Labels: exclude-from-changelog

#713 Re-implement quota API support in golang service broker.
  .github/workflows/postgres.yaml
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/quota/quota_management_client.go
  src/autoscaler/api/quota/quota_management_client_test.go
  src/autoscaler/api/quota/quota_suite_test.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/fakes/fake_binding_db.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_suite_test.go
Labels: enhancement, go

#724 Ensure defer is called before rows.Next()
  src/autoscaler/db/sqldb/binding_sqldb.go
Labels: bug

#723 Experimental .envrc file to configure golang asdf path
  .envrc
Labels: exclude-from-changelog

#732 Re-implement plan check in golang service broker
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/plancheck/plan_checker.go
  src/autoscaler/api/plancheck/plan_checker_suite_test.go
  src/autoscaler/api/plancheck/plan_checker_test.go
  src/autoscaler/api/quota/quota_management_client.go
Labels: enhancement

#733 Handle orphaned bindings
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/fakes/fake_binding_db.go
Labels: enhancement
