Repository cloudfoundry/app-autoscaler, pull requests merged in 2021-11, with the labels that each got.

#757 Updateable plans feature
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/plancheck/plan_checker_test.go
Labels: enhancement, accepted, go

#771 merge pr 21 test
  src/autoscaler/api/brokerserver/broker_handler_test.go
Labels: unscheduled, exclude-from-changelog

#776 Fix quota management broker responses
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/quota/quota_management_client.go
Labels: unscheduled

#778 Remove todos
  src/autoscaler/api/brokerserver/broker_handler.go
Labels: unscheduled

#777 Wrap maps with locks for concurrent access
  src/autoscaler/cf/client.go
  src/autoscaler/cf/service_instances.go
Labels: unscheduled

#779 Gosec updates after golangci-lint upgrade
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_suite_test.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/routes/routes.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
Labels: unscheduled

#775 Unflake tests
  src/autoscaler/api/plancheck/plan_checker_test.go
Labels: unscheduled

#783 refactor credential by interface
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/cred_helper/interface.go
  src/autoscaler/api/custom_metrics_cred_helper/cred_helper.go
  src/autoscaler/api/custom_metrics_cred_helper/cred_helper_suite_test.go
  src/autoscaler/api/custom_metrics_cred_helper/cred_helper_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
  src/autoscaler/metricsforwarder/server/auth/basic_auth.go
  src/autoscaler/metricsforwarder/server/auth_test.go
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsforwarder/server/server_suite_test.go
Labels: unscheduled

#784 Convert custom_metrics_cred_helper to a hashicorp plugin
  Makefile
  src/autoscaler/Makefile
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/cred_helper/config.go
  src/autoscaler/api/cred_helper/interface.go
  src/autoscaler/api/cred_helper/loader.go
  src/autoscaler/api/cred_helper/plugin.go
  src/autoscaler/api/cred_helper/rpc.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/custom-metrics-cred-helper-plugin/cmd/custom-metrics-cred-helper-plugin/main.go
  src/autoscaler/custom-metrics-cred-helper-plugin/internal/cred_helper.go
  src/autoscaler/custom-metrics-cred-helper-plugin/internal/cred_helper_suite_test.go
  src/autoscaler/custom-metrics-cred-helper-plugin/internal/cred_helper_test.go
  src/autoscaler/db/db.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/integration/components_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/server/auth/basic_auth.go
  src/autoscaler/metricsforwarder/server/auth_test.go
  src/autoscaler/metricsforwarder/server/server_suite_test.go
  src/autoscaler/metricsforwarder/server/server_test.go
Labels: enhancement, unscheduled

#785 Addressing review comments from hashicorp plugin PR
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/cred_helper/config.go
  src/autoscaler/cred_helper/interface.go
  src/autoscaler/cred_helper/loader.go
  src/autoscaler/cred_helper/plugin.go
  src/autoscaler/cred_helper/rpc.go
  src/autoscaler/custom-metrics-cred-helper-plugin/cmd/custom-metrics-cred-helper-plugin/main.go
  src/autoscaler/custom-metrics-cred-helper-plugin/internal/cred_helper.go
  src/autoscaler/custom-metrics-cred-helper-plugin/internal/cred_helper_test.go
  src/autoscaler/db/db.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
  src/autoscaler/metricsforwarder/server/server.go
Labels: unscheduled

#787 Loads plugin from config file for metrics forwarder
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/cred_helper/loader.go
  src/autoscaler/go.mod
  src/autoscaler/integration/components_test.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
Labels: unscheduled

#789 Switch basic auth fallback logging to debug
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
Labels: unscheduled

#788 Attempt to shutdown plugin correctly
  .envrc
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/cred_helper/loader.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  style-guide/google-format-ci-v0.1.sh
Labels: bug, unscheduled

#794 Initial impl of stored procedure based binding creds
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/cred_helper/loader.go
  src/autoscaler/cred_helper/plugin/config.go
  src/autoscaler/cred_helper/plugin/loader.go
  src/autoscaler/cred_helper/plugin/plugin.go
  src/autoscaler/cred_helper/plugin/rpc.go
  src/autoscaler/custom-metrics-cred-helper-plugin/cmd/custom-metrics-cred-helper-plugin/main.go
  src/autoscaler/custom-metrics-cred-helper-plugin/custom_metrics/cred_helper.go
  src/autoscaler/custom-metrics-cred-helper-plugin/custom_metrics/cred_helper_suite_test.go
  src/autoscaler/custom-metrics-cred-helper-plugin/custom_metrics/cred_helper_test.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb.go
  src/autoscaler/fakes/fake_storedprocedure_db.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/integration/components_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/models/custom_metrics.go
  src/autoscaler/models/stored_procedure.go
  src/autoscaler/storedprocedure/storedprocedure_cred_helper.go
Labels: unscheduled

#792 adding action/cache for artifacts
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
Labels: unscheduled

#796 Remove cert verification from xfcc header
  scripts/generate_test_certs.sh
  src/autoscaler/Makefile
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
  src/autoscaler/metricsforwarder/server/auth/xfcc_auth.go
  src/autoscaler/metricsforwarder/server/auth_test.go
  src/autoscaler/metricsforwarder/server/server.go
  style-guide/golangci-lint-0.1.sh
Labels: unscheduled

#797 Remove cred-helper plugin impl
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/cred_helper/cred_helper_suite_test.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper_test.go
  src/autoscaler/cred_helper/interface.go
  src/autoscaler/cred_helper/plugin/config.go
  src/autoscaler/cred_helper/plugin/loader.go
  src/autoscaler/cred_helper/plugin/plugin.go
  src/autoscaler/cred_helper/plugin/rpc.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper.go
  src/autoscaler/custom-metrics-cred-helper-plugin/cmd/custom-metrics-cred-helper-plugin/main.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/integration/components_test.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
Labels: unscheduled

#795 Adds initial default policy documentation
  docs/Readme.md
Labels: unscheduled

#800 Adding preconditions around primarykey addition
  src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml
Labels: bug

#799 Fix the make clean target
  src/autoscaler/Makefile
Labels: bug

#803 Using server:port as the node address when forwarding metrics
  src/autoscaler/eventgenerator/aggregator/metricPoller.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/metricsserver/collector/collector_suite_test.go
  src/autoscaler/metricsserver/collector/config.go
  src/autoscaler/metricsserver/collector/server.go
Labels: unscheduled

#804 Added unit tests for stored procedure db impl
  .tool-versions
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper_test.go
  src/autoscaler/cred_helper/interface.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper_test.go
Labels: unscheduled
