Repository cloudfoundry/app-autoscaler, pull requests merged in 2021-08, with the labels that each got.

#665 Fix: added the "unconvert" linter and fixed some unused parameter warnings
  src/autoscaler/.golangci.yaml
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/cf/app.go
  src/autoscaler/db/sqldb/lock_sqldb.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/eventgenerator/config/config_test.go
  src/autoscaler/eventgenerator/generator/appEvaluationManager_test.go
  src/autoscaler/metricsserver/collector/collector_test.go
  src/autoscaler/metricsserver/config/config_test.go
Labels: unscheduled

#657 Stops the tests from triggering the firewall on macos
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/eventgenerator/server/server.go
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsserver/collector/server.go
  src/autoscaler/metricsserver/collector/ws_server.go
  src/autoscaler/scalingengine/server/server.go
Labels: unscheduled

#666 aas82 configure Checkstyle for Java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/HealthConfig.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/dao/GenericDao.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/dao/GenericDaoImpl.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/dao/PolicyJsonDaoImpl.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/entity/ActiveScheduleEntity.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/entity/BitsetUserType.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/entity/RecurringScheduleEntity.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/entity/ScheduleEntity.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/entity/SpecificDateScheduleEntity.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/health/DbStatusCollector.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/health/HealthExporter.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/rest/model/SynchronizeResult.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/util/DataValidationHelper.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/util/RecurringScheduleTime.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/util/SpecificDateScheduleDateTime.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/util/error/InternalCodingError.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/util/error/ValidationErrorResult.java
  scheduler/src/main/resources/log4j2.xml
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplicationTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/dao/ActiveScheduleDaoImplFailureTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/dao/RecurringScheduleDaoImplTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/dao/SpecificDateScheduleDaoImplTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleJobTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerCreateScheduleAndNofifyScalingEngineTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleSyncRestControllerTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleJobManagerTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManagerTest.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/ApplicationPolicyBuilder.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/EmbeddedTomcatUtil.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/RecurringScheduleEntitiesBuilder.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/ScheduleBuilder.java
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/TestDataSetupHelper.java
  style-guide/checkstyle_suppressions.xml
  style-guide/google_checks.xml
  style-guide/inspect-java-format-0.1.sh
Labels: unscheduled

#667 Adding errorlint to the linter
  src/autoscaler/.golangci.yaml
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/publicapiserver/middleware.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/db/sqldb/lock_sqldb.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/helpers/json_redacter_with_url_creds.go
  src/autoscaler/helpers/time_logger_format.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/operator/applicationsyncer.go
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/testhelpers/fakeLoggregator.go
  style-guide/README.md
Labels: unscheduled

#675 Revert "Stops the tests from triggering the firewall on macos"
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/eventgenerator/server/server.go
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsserver/collector/server.go
  src/autoscaler/metricsserver/collector/ws_server.go
  src/autoscaler/scalingengine/server/server.go
Labels: unscheduled

#664 Don't trigger cooldown if scaling was ignored
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
Labels: unscheduled

#676 Do not run tests after merge
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
Labels: unscheduled

#674 [AAS-82] add java checkstyle linter
  .github/workflows/java-ci-lint.yaml
  format_checkstyle.go
  scheduler/pom.xml
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplication.java
  scheduler/styleguide/intellij-java-google-style-v0.1.xml
  style-guide/checkstyle.properties
  style-guide/checkstyle_suppressions.xml
  style-guide/google-format-ci-v0.1.sh
  style-guide/google_checks.xml
  style-guide/inspect-java-format-0.1.sh
Labels: unscheduled

#678 Disable keepGoing in test suite to make them fail fast
  src/autoscaler/Makefile
Labels: unscheduled

#682 [AAS-82] Test Golang and Java Linters
  README.md
  style-guide/README.md
  style-guide/inspect-java-format-0.1.sh
Labels: unscheduled

#685 [AAS-82] update docs
  style-guide/README.md
Labels: unscheduled, chore

#686 Add primary key on scalinghistory table
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml
Labels: bug, unscheduled

#687 Update to build instructions
  README.md
Labels: unscheduled, chore

#684 Fix: enabled the prometheus metrics endpoint and fixed tests to properly assert
  app-autoscaler.iml
  scheduler/pom.xml
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplication.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/HealthConfig.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/MetricsConfig.java
  scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/MetricsConfiguration.java
  scheduler/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  scheduler/src/main/resources/application-mysql.properties
  scheduler/src/main/resources/application.properties
  scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/health/SchedulerHealthEndpointTest.java
  style-guide/README.md
  style-guide/google-format-ci-v0.1.sh
  style-guide/google_checks.xml
  style-guide/inspect-java-format-0.1.sh
Labels: bug, unscheduled
